"""add favorite_meal column

Revision ID: 468e9e8dc112
Revises: 4e78a4a08413
Create Date: 2026-04-15 12:26:49.751664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468e9e8dc112'
down_revision: Union[str, Sequence[str], None] = '4e78a4a08413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_meal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_meal')
    # ### end Alembic commands ###
