"""stored access token and refresh token for oauth

Revision ID: cbc3f1c34c5b
Revises: b7b71754f5b2
Create Date: 2026-05-04 13:00:00.113741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc3f1c34c5b'
down_revision: Union[str, Sequence[str], None] = 'b7b71754f5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    # ### end Alembic commands ###
